version: '3'

services:
  database:
    container_name: mnist-classifier-db
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_DB="MNIST-web-service"
  backend:
    container_name: minst-classifier-backend
    build: ./backend
    image: mnist-classifier-backend
    ports:
      - '3000:3000'
    volumes:
      - './backend:/app:rw'
      - '/app/node_modules'
    depends_on:
      - database

volumes:
  db:
    driver: local
